import React from "react";

export const S = {
  page: {
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    background: "#f8fafc",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    width: "100%",
    maxWidth: "1000px",
    margin: "0 auto",
    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.05), 0 4px 6px -4px rgb(0 0 0 / 0.05)",
    borderLeft: "1px solid #e2e8f0",
    borderRight: "1px solid #e2e8f0",
    boxSizing: "border-box" as const,
  },
  header: {
    background: "#1e40af",
    color: "#fff",
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { fontSize: 16, fontWeight: 700, margin: 0 },
  tabBar: {
    display: "flex",
    background: "#fff",
    borderBottom: "1px solid #e2e8f0",
    padding: "0 12px",
    overflowX: "auto" as const,
  },
  tab: (active: boolean): React.CSSProperties => ({
    padding: "10px 14px",
    border: "none",
    background: "none",
    cursor: "pointer",
    borderBottom: active ? "2px solid #2563eb" : "2px solid transparent",
    color: active ? "#2563eb" : "#64748b",
    fontWeight: active ? 600 : 400,
    fontSize: 13,
    flexShrink: 0,
    whiteSpace: "nowrap" as const,
  }),
  content: { flex: 1, padding: 20, overflowY: "auto" as const },
  card: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  label: { fontSize: 12, color: "#64748b", marginBottom: 3 },
  value: { fontWeight: 600, wordBreak: "break-all" as const },
  badgeGreen: {
    display: "inline-block",
    background: "#dcfce7",
    color: "#166534",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  badgeRed: {
    display: "inline-block",
    background: "#fee2e2",
    color: "#991b1b",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  badgeBlue: {
    display: "inline-block",
    background: "#dbeafe",
    color: "#1e40af",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  badgeGray: {
    display: "inline-block",
    background: "#f1f5f9",
    color: "#64748b",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  badgeAmber: {
    display: "inline-block",
    background: "#fef3c7",
    color: "#92400e",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
  },
  btnPrimary: {
    padding: "8px 14px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
  },
  btnOutline: {
    padding: "8px 14px",
    background: "#fff",
    color: "#374151",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
  },
  btnSmall: {
    padding: "5px 10px",
    background: "#fff",
    color: "#374151",
    border: "1px solid #cbd5e1",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 12,
  },
  input: {
    width: "100%",
    padding: "7px 10px",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    fontSize: 13,
    boxSizing: "border-box" as const,
    marginTop: 4,
  },
  error: { color: "#dc2626", fontSize: 12, marginTop: 6 },
  success: { color: "#166534", fontSize: 12, marginTop: 6 },
  warn: {
    padding: "8px 10px",
    background: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: 6,
    color: "#92400e",
    fontSize: 12,
    marginBottom: 12,
  },
  hint: { color: "#94a3b8", fontSize: 11, marginTop: 4 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  previewBox: {
    aspectRatio: "16/9",
    background: "#0f172a",
    borderRadius: 8,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  divider: { borderTop: "1px solid #f1f5f9", margin: "12px 0" },
  pairingContainer: {
    width: "100%",
    maxWidth: "480px",
    padding: 32,
    background: "#fff",
    borderRadius: 12,
    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.05), 0 4px 6px -4px rgb(0 0 0 / 0.05)",
    border: "1px solid #e2e8f0",
  },
};
